#!/bin/sh
rm -rf Blending/PixelCombine/lib
rm -rf Blending/TextureBlend/lib
rm -rf Drawing/AntiAliasing/lib
rm -rf Drawing/ArrowHead/lib
rm -rf Drawing/Benchmark/lib
rm -rf Drawing/Blurs/lib
rm -rf Drawing/Clipper/lib
rm -rf Drawing/CubicSpline/lib
rm -rf Drawing/Curves/lib
rm -rf Drawing/GammaCorrection/lib
rm -rf Drawing/GradFills/lib
rm -rf Drawing/GradLines/lib
rm -rf Drawing/GradSampler/lib
rm -rf Drawing/LineStippling/lib
rm -rf Drawing/Lion/lib
rm -rf Drawing/MeshGradients/lib
rm -rf Drawing/Polygons/lib
rm -rf Drawing/RenderText/lib
rm -rf Drawing/ScatterPlot/lib
rm -rf Drawing/TextVPR/lib
rm -rf Drawing/VertexReduction/lib
rm -rf General/ByteMaps/lib
rm -rf General/Image32/lib
rm -rf General/Mandelbrot/lib
rm -rf General/Rotate/lib
rm -rf Layers/ImgView_Layers/lib
rm -rf Layers/RotLayer/lib
rm -rf Layers/Sprites/lib
rm -rf Resampling/NestedSampling/lib
rm -rf Resampling/PixelF/lib
rm -rf Resampling/Resamplers/lib
rm -rf Transformation/ImgWarping/lib
rm -rf Transformation/Transform/lib
rm -rf Transformation/Visualization/lib

