@echo off
rmdir /S /Q Blending\PixelCombine\lib
rmdir /S /Q Blending\TextureBlend\lib
rmdir /S /Q Drawing\AntiAliasing\lib
rmdir /S /Q Drawing\ArrowHead\lib
rmdir /S /Q Drawing\Blurs\lib
rmdir /S /Q Drawing\Clipper\lib
rmdir /S /Q Drawing\CubicSpline\lib
rmdir /S /Q Drawing\Curves\lib
rmdir /S /Q Drawing\GammaCorrection\lib
rmdir /S /Q Drawing\GradFills\lib
rmdir /S /Q Drawing\GradLines\lib
rmdir /S /Q Drawing\GradSampler\lib
rmdir /S /Q Drawing\LineStippling\lib
rmdir /S /Q Drawing\MeshGradients\lib
rmdir /S /Q Drawing\Polygons\lib
rmdir /S /Q Drawing\RenderText\lib
rmdir /S /Q Drawing\ScatterPlot\lib
rmdir /S /Q Drawing\TextVPR\lib
rmdir /S /Q General\ByteMaps\lib
rmdir /S /Q General\Image32\lib
rmdir /S /Q General\Mandelbrot\lib
rmdir /S /Q General\Rotate\lib
rmdir /S /Q Layers\ImgView_Layers\lib
rmdir /S /Q Layers\RotLayer\lib
rmdir /S /Q Layers\Sprites\lib
rmdir /S /Q Resampling\NestedSampling\lib
rmdir /S /Q Resampling\PixelF\lib
rmdir /S /Q Resampling\Resamplers\lib
rmdir /S /Q Transformation\ImgWarping\lib
rmdir /S /Q Transformation\Transform\lib
rmdir /S /Q Transformation\Visualization\lib
